Repository eliashaeussler/cache-warmup, pull requests merged in 2023-02, with the labels that each got.

#197 [!!!][FEATURE] Introduce response handlers
  src/Crawler/ConcurrentCrawler.php
  src/Crawler/ConcurrentCrawlerTrait.php
  src/Crawler/OutputtingCrawler.php
  src/Crawler/VerboseCrawlerInterface.php
  src/Http/Message/Handler/OutputtingProgressHandler.php
  src/Http/Message/Handler/ResponseHandlerInterface.php
  src/Http/Message/Handler/ResultCollectorHandler.php
  src/Http/Message/RequestPoolFactory.php
  tests/Unit/Crawler/ConcurrentCrawlerTest.php
  tests/Unit/Crawler/DummyVerboseCrawler.php
  tests/Unit/Crawler/OutputtingCrawlerTest.php
  tests/Unit/Http/Message/Handler/OutputtingProgressHandlerTest.php
  tests/Unit/Http/Message/Handler/ResultCollectorHandlerTest.php
  tests/Unit/Http/Message/RequestPoolFactoryTest.php
Labels: enhancement, breaking

#200 [TASK] Enable automatic code migration with Rector
  .gitattributes
  .github/workflows/cgl.yaml
  composer.json
  composer.lock
  rector.php
  src/Crawler/ConcurrentCrawler.php
  src/Crawler/OutputtingCrawler.php
  src/Exception/InvalidCrawlerOptionException.php
  src/Http/Message/Handler/OutputtingProgressHandler.php
  src/Http/Message/Handler/ResultCollectorHandler.php
  tests/Unit/CacheWarmupResultProcessorTrait.php
  tests/Unit/Crawler/AbstractConfigurableCrawlerTest.php
  tests/Unit/Exception/InvalidCrawlerOptionExceptionTest.php
Labels: maintenance

#201 [BUGFIX] Properly handle errors during XML parsing
  src/Mapper/Source/XmlSource.php
Labels: bug

#202 [FEATURE] Introduce compact and verbose progress handlers
  README.md
  src/Command/CacheWarmupCommand.php
  src/Crawler/OutputtingCrawler.php
  src/Http/Message/Handler/CompactProgressHandler.php
  src/Http/Message/Handler/VerboseProgressHandler.php
  tests/Unit/BufferedConsoleOutput.php
  tests/Unit/Command/CacheWarmupCommandTest.php
  tests/Unit/Crawler/OutputtingCrawlerTest.php
  tests/Unit/Http/Message/Handler/CompactProgressHandlerTest.php
  tests/Unit/Http/Message/Handler/VerboseProgressHandlerTest.php
Labels: enhancement

#206 [TASK] Use heredoc for command help
  src/Command/CacheWarmupCommand.php
Labels: maintenance

#209 [!!!][FEATURE] Use Guzzle client everywhere
  composer.json
  composer.lock
  src/CacheWarmer.php
  src/Command/CacheWarmupCommand.php
  src/Xml/XmlParser.php
  tests/Unit/Fixtures/DummyClient.php
  tests/Unit/Xml/XmlParserTest.php
Labels: enhancement, breaking

#211 [FEATURE] Introduce CrawlerFactory
  src/Command/CacheWarmupCommand.php
  src/Crawler/CrawlerFactory.php
  src/Exception/InvalidCrawlerException.php
  tests/Unit/Command/CacheWarmupCommandTest.php
  tests/Unit/Crawler/CrawlerFactoryTest.php
  tests/Unit/Exception/InvalidCrawlerExceptionTest.php
Labels: enhancement

#208 [FEATURE] Introduce endless mode with `--repeat-after` option
  README.md
  phpunit.coverage.xml
  phpunit.xml
  src/Command/CacheWarmupCommand.php
  tests/Unit/Command/CacheWarmupCommandTest.php
  tests/Unit/Crawler/DummyCrawler.php
Labels: enhancement

#213 [TASK] Use `eliashaeussler/phpstan-config`
  composer.json
  composer.lock
Labels: maintenance

#216 [TASK] Disable Dependabot in favor of Renovate
  .github/dependabot.yml
  .github/workflows/auto-merge.yaml
Labels: maintenance

#223 [TASK] Run workflows on renovate branches
  .github/workflows/cgl.yaml
  .github/workflows/tests.yaml
Labels: maintenance

#225 [TASK] Move parsing of crawler options to CrawlerFactory
  src/Command/CacheWarmupCommand.php
  src/Crawler/CrawlerFactory.php
  src/Exception/InvalidCrawlerOptionException.php
  tests/Unit/Command/CacheWarmupCommandTest.php
  tests/Unit/Crawler/CrawlerFactoryTest.php
Labels: maintenance

#226 [BUGFIX] Hide crawler output if non-verbose formatter is selected
  src/Command/CacheWarmupCommand.php
  tests/Unit/Command/CacheWarmupCommandTest.php
Labels: bug

#228 [BUGFIX] Avoid dependency to intl extension
  composer.json
  composer.lock
  src/Time/Duration.php
Labels: bug

#230 [BUGFIX] Run CodeClimate only if env exists
  .github/workflows/tests.yaml
Labels: bug

#229 [BUGFIX] Fix label for security fixes
  .github/release.yml
Labels: bug

#231 [TASK] Improve listing of invalid crawler options in exception message
  src/Exception/InvalidCrawlerOptionException.php
  tests/Unit/Crawler/AbstractConfigurableCrawlerTest.php
  tests/Unit/Exception/InvalidCrawlerOptionExceptionTest.php
Labels: maintenance

#233 [!!!][FEATURE] Introduce crawling strategies
  README.md
  src/CacheWarmer.php
  src/Command/CacheWarmupCommand.php
  src/Crawler/Strategy/CrawlingStrategy.php
  src/Crawler/Strategy/SortByChangeFrequencyStrategy.php
  src/Crawler/Strategy/SortByLastModificationDateStrategy.php
  src/Crawler/Strategy/SortByPriorityStrategy.php
  src/Crawler/Strategy/SortingStrategy.php
  tests/Unit/CacheWarmerTest.php
  tests/Unit/Crawler/Strategy/SortByChangeFrequencyStrategyTest.php
  tests/Unit/Crawler/Strategy/SortByLastModificationDateStrategyTest.php
  tests/Unit/Crawler/Strategy/SortByPriorityStrategyTest.php
Labels: enhancement, breaking
